// Three.js rendering of worlds generated by the Rust core. Rust decides
// what exists; this file decides how each kind looks. The camera is fixed
// and players rotate the planet itself.

import * as THREE from 'three';

const UP = new THREE.Vector3(0, 1, 0);

// seeded helpers, so all players see the same textures
function mulberry32(seed) {
  let a = seed >>> 0;
  return () => {
    a |= 0; a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

function planetTexture(seed) {
  const rnd = mulberry32(seed ^ 0x9e3779b9);
  const c = document.createElement('canvas');
  c.width = 1024; c.height = 512;
  const ctx = c.getContext('2d');
  const bases = ['#4e8f3a', '#478440', '#5a9440', '#3f7d33'];
  ctx.fillStyle = bases[(rnd() * bases.length) | 0];
  ctx.fillRect(0, 0, 1024, 512);
  const blob = (colors, n, rx, ry, alpha) => {
    ctx.globalAlpha = alpha;
    for (let i = 0; i < n; i++) {
      ctx.fillStyle = colors[(rnd() * colors.length) | 0];
      ctx.beginPath();
      ctx.ellipse(rnd() * 1024, rnd() * 512, rx[0] + rnd() * rx[1], ry[0] + rnd() * ry[1], rnd() * 3, 0, 7);
      ctx.fill();
    }
  };
  blob(['#457f33', '#5a9c44', '#3f7a2e', '#63a94c', '#528c3f'], 700 + rnd() * 500, [8, 26], [5, 16], 1);
  blob(['#c9b878', '#d4c48a', '#b8a86c'], 4 + rnd() * 10, [20, 50], [12, 25], 0.7);
  blob(['#8d8d8d', '#9a9a94', '#7f8287'], 15 + rnd() * 25, [25, 55], [15, 30], 0.85);
  ctx.globalAlpha = 1;
  const t = new THREE.CanvasTexture(c);
  t.colorSpace = THREE.SRGBColorSpace;
  t.wrapS = t.wrapT = THREE.RepeatWrapping;
  return t;
}

function stripeTexture() {
  const c = document.createElement('canvas');
  c.width = c.height = 64;
  const ctx = c.getContext('2d');
  for (let i = 0; i < 8; i++) {
    ctx.fillStyle = i % 2 ? '#ffffff' : '#e02020';
    ctx.fillRect(0, i * 8, 64, 8);
  }
  const t = new THREE.CanvasTexture(c);
  t.colorSpace = THREE.SRGBColorSpace;
  return t;
}

// per-kind scenery geometry and materials
function kindParts(stripes) {
  const lam = (opts) => new THREE.MeshLambertMaterial(opts);
  const g = {
    cyl: (a, b, h, s, ty) => { const x = new THREE.CylinderGeometry(a, b, h, s); x.translate(0, ty, 0); return x; },
    box: (a, b, c, ty) => { const x = new THREE.BoxGeometry(a, b, c); x.translate(0, ty, 0); return x; },
    sph: (r, ty, half) => {
      const x = half ? new THREE.SphereGeometry(r, 10, 6, 0, Math.PI * 2, 0, Math.PI / 2)
                     : new THREE.SphereGeometry(r, 8, 7);
      x.translate(0, ty, 0); return x;
    },
    cone: (r, h, s, ty) => { const x = new THREE.ConeGeometry(r, h, s); x.translate(0, ty, 0); return x; },
    ico: (r) => new THREE.IcosahedronGeometry(r, 0),
  };
  // per kind: [{geo, mat, colored}] where colored picks the color stream
  return {
    pine: [
      { geo: g.cyl(0.05, 0.07, 0.3, 6, 0.15), mat: lam({ color: 0x6b4a2b }), colored: 0 },
      { geo: g.cone(0.3, 0.85, 7, 0.72), mat: lam(), colored: 1 },
    ],
    tree: [
      { geo: g.cyl(0.05, 0.08, 0.35, 6, 0.17), mat: lam({ color: 0x7a5230 }), colored: 0 },
      { geo: g.sph(0.28, 0.52, false), mat: lam(), colored: 1 },
    ],
    bush: [{ geo: g.sph(0.16, 0.1, false), mat: lam(), colored: 1 }],
    building: [{ geo: g.box(1, 1, 1, 0.5), mat: lam(), colored: 1 }],
    house: [
      { geo: g.cone(0.42, 0.4, 4, 0.6), mat: lam(), colored: 1 },
      { geo: g.box(0.55, 0.42, 0.55, 0.21), mat: lam(), colored: 2 },
    ],
    tower: [{ geo: g.cyl(0.28, 0.32, 1, 10, 0.5), mat: lam(), colored: 1 }],
    dome: [{ geo: g.sph(0.35, 0, true), mat: lam(), colored: 1 }],
    pond: [{ geo: g.cyl(0.5, 0.5, 0.04, 12, 0.02), mat: lam({ color: 0x3d78c8 }), colored: 0 }],
    car: [{ geo: g.box(0.28, 0.12, 0.15, 0.06), mat: lam(), colored: 1 }],
    rock: [{ geo: g.ico(0.2), mat: lam({ color: 0x8a8f96 }), colored: 0 }],
    decoy: [{ geo: g.cyl(0.09, 0.11, 0.9, 10, 0.45), mat: lam({ map: stripes }), colored: 0 }],
  };
}

function buildWaldo(stripes) {
  const grp = new THREE.Group();
  const lam = (o) => new THREE.MeshLambertMaterial(o);
  const skin = lam({ color: 0xf2c896 }), blue = lam({ color: 0x2b4fd6 });
  const striped = lam({ map: stripes }), dark = lam({ color: 0x3a2a1a });
  const add = (geo, mat, y, extra) => {
    const m = new THREE.Mesh(geo, mat);
    m.position.y = y;
    if (extra) extra(m);
    grp.add(m);
    return m;
  };
  add(new THREE.CylinderGeometry(0.085, 0.095, 0.18, 10), blue, 0.09);
  add(new THREE.CylinderGeometry(0.1, 0.11, 0.24, 12), striped, 0.30);
  add(new THREE.CylinderGeometry(0.032, 0.032, 0.2, 8), striped, 0.33,
    (m) => { m.position.x = 0.13; m.rotation.z = 0.35; });
  add(new THREE.CylinderGeometry(0.032, 0.032, 0.2, 8), striped, 0.33,
    (m) => { m.position.x = -0.13; m.rotation.z = -0.35; });
  add(new THREE.SphereGeometry(0.095, 14, 12), skin, 0.52);
  add(new THREE.SphereGeometry(0.098, 12, 8, 0, Math.PI * 2, 0, Math.PI * 0.45), dark, 0.535);
  add(new THREE.CylinderGeometry(0.075, 0.09, 0.09, 12), striped, 0.615);
  add(new THREE.SphereGeometry(0.035, 8, 8), lam({ color: 0xe02020 }), 0.665);
  return grp;
}

// renderer
export class GameRenderer {
  constructor(canvas) {
    this.canvas = canvas;
    this.renderer = new THREE.WebGLRenderer({ canvas, antialias: true });
    this.renderer.setPixelRatio(Math.min(devicePixelRatio, 2));
    this.renderer.setSize(innerWidth, innerHeight);

    this.scene = new THREE.Scene();
    this.scene.background = new THREE.Color(0x0b1026);
    this.camera = new THREE.PerspectiveCamera(45, innerWidth / innerHeight, 0.1, 500);
    this.camDir = new THREE.Vector3(0, 9, 30).normalize();
    this.zoom = 1;
    this.baseDist = 40;
    this.fitRadius = 17;

    this.scene.add(new THREE.HemisphereLight(0xbfd9ff, 0x3d2f1f, 0.9));
    const sun = new THREE.DirectionalLight(0xfff2d9, 1.6);
    sun.position.set(18, 25, 20);
    const fill = new THREE.DirectionalLight(0x8899ff, 0.35);
    fill.position.set(-15, -10, -10);
    this.scene.add(sun, fill);

    {
      const g = new THREE.BufferGeometry();
      const n = 900, pos = new Float32Array(n * 3);
      for (let i = 0; i < n; i++) {
        const v = new THREE.Vector3().randomDirection().multiplyScalar(150 + Math.random() * 100);
        pos.set([v.x, v.y, v.z], i * 3);
      }
      g.setAttribute('position', new THREE.BufferAttribute(pos, 3));
      this.scene.add(new THREE.Points(g, new THREE.PointsMaterial({ color: 0xffffff, size: 0.7 })));
    }

    this.planet = new THREE.Group();
    this.scene.add(this.planet);

    this.stripes = stripeTexture();
    this.kinds = kindParts(this.stripes);
    this.disposables = [];

    this.ground = new THREE.Mesh(
      new THREE.BufferGeometry(),
      new THREE.MeshLambertMaterial({ side: THREE.DoubleSide })
    );
    this.planet.add(this.ground);

    this.waldo = buildWaldo(this.stripes);
    this.planet.add(this.waldo);

    const outlineMat = new THREE.MeshBasicMaterial({
      color: 0xffffff, depthTest: false, depthWrite: false, transparent: true, opacity: 0.95,
    });
    this.outline = buildWaldo(this.stripes);
    this.outline.traverse((o) => { if (o.isMesh) { o.material = outlineMat; o.renderOrder = 999; } });
    this.outline.scale.setScalar(1.15);
    this.outline.visible = false;
    this.waldo.add(this.outline);

    this.foundRing = new THREE.Mesh(
      new THREE.TorusGeometry(0.9, 0.06, 8, 40),
      new THREE.MeshBasicMaterial({ color: 0xffe14a })
    );
    this.foundRing.visible = false;
    this.planet.add(this.foundRing);

    this.missRing = new THREE.Mesh(
      new THREE.TorusGeometry(0.4, 0.05, 8, 32),
      new THREE.MeshBasicMaterial({ color: 0xff4040, transparent: true })
    );
    this.missRing.visible = false;
    this.missTime = -1e9;
    this.planet.add(this.missRing);

    this.raycaster = new THREE.Raycaster();
    this.pointerV = new THREE.Vector2();

    addEventListener('resize', () => {
      this.camera.aspect = innerWidth / innerHeight;
      this.renderer.setSize(innerWidth, innerHeight);
      this.fitCamera();
    });
    this.fitCamera();

    this.renderer.setAnimationLoop(() => this.tick());
  }

  // ----- camera -----
  setZoom(z) {
    this.zoom = THREE.MathUtils.clamp(z, 1, 5);
    this.camera.position.copy(this.camDir).multiplyScalar(this.baseDist / this.zoom);
    this.camera.lookAt(0, 0, 0);
  }
  fitCamera() {
    this.camera.aspect = innerWidth / innerHeight;
    const vFov = THREE.MathUtils.degToRad(this.camera.fov);
    const hFov = 2 * Math.atan(Math.tan(vFov / 2) * this.camera.aspect);
    this.baseDist = this.fitRadius / Math.tan(Math.min(vFov, hFov) / 2);
    this.setZoom(this.zoom);
    this.camera.updateProjectionMatrix();
  }

  rotatePlanet(dx, dy) {
    const speed = 0.006 / Math.sqrt(this.zoom);
    const q = new THREE.Quaternion();
    this.planet.quaternion.premultiply(q.setFromAxisAngle(UP, dx * speed));
    this.planet.quaternion.premultiply(q.setFromAxisAngle(new THREE.Vector3(1, 0, 0), dy * speed));
  }

  // ----- world lifecycle -----
  clearWorld() {
    for (const d of this.disposables) {
      this.planet.remove(d);
      d.geometry?.dispose();
    }
    this.disposables = [];
    this.outline.visible = false;
    this.foundRing.visible = false;
    this.missRing.visible = false;
    this.waldo.visible = false;
  }

  /** Build the scene from a WASM WorldHandle + its parsed metadata. */
  buildWorld(handle, meta) {
    this.clearWorld();

    this.ground.geometry.dispose();
    const geo = new THREE.BufferGeometry();
    geo.setAttribute('position', new THREE.BufferAttribute(handle.positions(), 3));
    geo.setAttribute('normal', new THREE.BufferAttribute(handle.normals(), 3));
    geo.setAttribute('uv', new THREE.BufferAttribute(handle.uvs(), 2));
    geo.setIndex(new THREE.BufferAttribute(handle.indices(), 1));
    this.ground.geometry = geo;
    this.ground.material.map?.dispose();
    this.ground.material.map = planetTexture(meta.seed);
    this.ground.material.needsUpdate = true;

    // transforms are 10 floats per instance: pos3 quat4 scale3
    const M = new THREE.Matrix4(), P = new THREE.Vector3(),
          Q = new THREE.Quaternion(), S = new THREE.Vector3(), C = new THREE.Color();
    meta.sets.forEach((set, si) => {
      const parts = this.kinds[set.kind];
      if (!parts || set.count === 0) return;
      const t = handle.setTransforms(si);
      const colorStreams = [null, handle.setColors(si), handle.setColors2(si)];
      for (const part of parts) {
        const im = new THREE.InstancedMesh(part.geo, part.mat, set.count);
        const colors = part.colored ? colorStreams[part.colored] : null;
        for (let i = 0; i < set.count; i++) {
          const o = i * 10;
          P.set(t[o], t[o + 1], t[o + 2]);
          Q.set(t[o + 3], t[o + 4], t[o + 5], t[o + 6]);
          S.set(t[o + 7], t[o + 8], t[o + 9]);
          im.setMatrixAt(i, M.compose(P, Q, S));
          if (colors && colors.length >= (i + 1) * 3) {
            im.setColorAt(i, C.setRGB(colors[i * 3], colors[i * 3 + 1], colors[i * 3 + 2]));
          }
        }
        im.instanceMatrix.needsUpdate = true;
        if (im.instanceColor) im.instanceColor.needsUpdate = true;
        this.planet.add(im);
        this.disposables.push(im);
      }
    });

    const w = meta.waldo;
    this.waldo.position.set(...w.pos);
    this.waldo.quaternion.set(...w.quat);
    this.waldo.scale.set(...w.scale);
    this.waldo.visible = true;

    this.fitRadius = meta.bounding_radius + 2.8;
    this.zoom = 1;
    this.fitCamera();

    // random orientation so nobody starts staring at Waldo
    this.planet.quaternion.setFromEuler(new THREE.Euler(
      Math.random() * Math.PI * 2, Math.random() * Math.PI * 2, Math.random() * Math.PI * 2));
  }

  // ----- guessing -----
  /** Raycast the planet surface and Waldo; returns planet-local {pos, normal} or null. */
  pickSurface(clientX, clientY) {
    this.pointerV.set((clientX / innerWidth) * 2 - 1, -(clientY / innerHeight) * 2 + 1);
    this.raycaster.setFromCamera(this.pointerV, this.camera);
    const hit = this.raycaster.intersectObjects([this.ground, this.waldo], true)[0];
    if (!hit) return null;
    // a click anywhere on Waldo's model counts as his location, even at
    // glancing angles where the ray would land on the ground far behind him
    for (let o = hit.object; o; o = o.parent) {
      if (o === this.waldo) {
        const pos = this.waldo.position.clone();
        return { pos, normal: pos.clone().normalize() };
      }
    }
    const pos = this.planet.worldToLocal(hit.point.clone());
    const normal = hit.face ? hit.face.normal.clone() : pos.clone().normalize();
    return { pos, normal };
  }

  /** Gold pulsing ring at Waldo. */
  markFound(waldoPos) {
    const p = new THREE.Vector3(...waldoPos);
    const n = p.clone().normalize();
    this.foundRing.position.copy(p).addScaledVector(n, 0.5);
    this.foundRing.quaternion.setFromUnitVectors(new THREE.Vector3(0, 0, 1), n);
    this.foundRing.visible = true;
  }

  /** Brief red ring where a wrong click landed. */
  showMiss(pick) {
    this.missRing.position.copy(pick.pos).addScaledVector(pick.normal, 0.05);
    this.missRing.quaternion.setFromUnitVectors(new THREE.Vector3(0, 0, 1), pick.normal);
    this.missRing.visible = true;
    this.missTime = performance.now();
  }

  revealWaldo(waldoPos) {
    this.outline.visible = true;
    this.markFound(waldoPos);
    // rotate the planet so Waldo faces the camera
    const p = new THREE.Vector3(...waldoPos);
    const target = this.camDir.clone();
    const current = p.clone().normalize().applyQuaternion(this.planet.quaternion);
    const fix = new THREE.Quaternion().setFromUnitVectors(current, target);
    this.planet.quaternion.premultiply(fix);
  }

  tick() {
    if (this.foundRing.visible) {
      this.foundRing.scale.setScalar(1 + 0.25 * Math.sin(performance.now() * 0.008));
    }
    if (this.missRing.visible) {
      const a = 1 - (performance.now() - this.missTime) / 1000;
      if (a <= 0) this.missRing.visible = false;
      else {
        this.missRing.material.opacity = a;
        this.missRing.scale.setScalar(1 + (1 - a) * 0.8);
      }
    }
    this.onTick?.();
    this.renderer.render(this.scene, this.camera);
  }
}
